name: physnet_torch
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.15.0
  - aiohttp=3.7.4.post0
  - alabaster=0.7.12
  - argh=0.26.2
  - arrow=1.2.1
  - ase=3.22.0
  - astroid=2.5.8
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - binaryornot=0.4.4
  - black=21.10b0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cookiecutter=1.6.0
  - cryptography=35.0.0
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.4.1
  - flake8=3.9.2
  - flask=2.0.2
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.70.0
  - glib-tools=2.70.0
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.41.1
  - icu=68.2
  - idna=3.1
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - inflection=0.5.1
  - intervaltree=3.0.2
  - ipykernel=6.4.2
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - isort=5.10.0
  - itsdangerous=2.0.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jinja2-time=0.2.0
  - jpeg=9d
  - jsonschema=4.1.2
  - jupyter_client=6.1.12
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - keyring=23.2.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libclang=11.1.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran
  - libglib=2.70.0
  - libiconv=1.16
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.3.0
  - libuv=1.42.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nspr=4.32
  - nss=3.71
  - numpy=1.21.2
  - numpy-base=1.21.2
  - numpydoc=1.1.0
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas
  - pandoc=2.16.1
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3.1
  - platformdirs=2.3.0
  - pluggy=1.0.0
  - poyo=0.5.0
  - prompt-toolkit=3.0.22
  - protobuf=3.19.1
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pylint=2.7.2
  - pyls-spyder=0.4.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python_abi=3.8
  - pytorch=1.10.0
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.1
  - qt=5.12.9
  - qtawesome=1.1.0
  - qtconsole=5.1.1
  - qtpy=1.11.2
  - readline=8.1
  - regex=2021.11.2
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rope=0.21.0
  - rsa=4.7.2
  - rtree=0.9.7
  - scipy=1.7.1
  - seaborn
  - setuptools=58.5.3
  - six=1.16.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.4.0
  - sphinx=4.2.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tbb=2021.4.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorboardx=2.4
  - testpath=0.5.0
  - textdistance=4.2.2
  - three-merge=0.1.1
  - tinycss2=1.1.0
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - ujson=4.2.0
  - urllib3=1.26.7
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - whichcraft=0.6.1
  - wrapt=1.12.1
  - wurlitzer=3.0.2
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
      -torch-ema==0.3
